/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.1
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Vec } from "./common";

export type PriceInput = { confidence: BigNumberish, exponent: BigNumberish, price: BigNumberish, publish_time: BigNumberish };
export type PriceOutput = { confidence: BN, exponent: number, price: BN, publish_time: BN };

export type ContractAbiConfigurables = {
  PYTH_CONTRACT_ID: string;
  FUEL_ETH_BASE_ASSET_ID: string;
};

interface ContractAbiInterface extends Interface {
  functions: {
    chain_id: FunctionFragment;
    get_price: FunctionFragment;
    update_fee: FunctionFragment;
    update_price_feeds: FunctionFragment;
    valid_time_period: FunctionFragment;
  };
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    chain_id: InvokeFunction<[], number>;
    get_price: InvokeFunction<[price_feed_id: string], PriceOutput>;
    update_fee: InvokeFunction<[update_data: Vec<Bytes>], BN>;
    update_price_feeds: InvokeFunction<[update_fee: BigNumberish, update_data: Vec<Bytes>], void>;
    valid_time_period: InvokeFunction<[], BN>;
  };
}
